# Generated by Django 3.2.19 on 2026-06-04 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_add_email_logging_and_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='emaillog',
            name='movies_email_user_date_log_idx',
        ),
        migrations.RemoveIndex(
            model_name='emaillog',
            name='movies_email_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='emaillog',
            name='movies_email_queue_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailqueueitem',
            name='movies_email_status_next_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailqueueitem',
            name='movies_email_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movie_rating_name_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='theater',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='emailqueueitem',
            name='template_name',
            field=models.CharField(default='emails/booking_confirmation.html', max_length=255),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['user', '-created_at'], name='movies_emai_user_id_015d95_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', '-created_at'], name='movies_emai_status_0d4d40_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email_queue_item', '-created_at'], name='movies_emai_email_q_352718_idx'),
        ),
        migrations.AddIndex(
            model_name='emailqueueitem',
            index=models.Index(fields=['status', 'next_attempt_at'], name='movies_emai_status_0099eb_idx'),
        ),
        migrations.AddIndex(
            model_name='emailqueueitem',
            index=models.Index(fields=['user', 'created_at'], name='movies_emai_user_id_12cae3_idx'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='movies.paymentorder'),
        ),
    ]
