# Generated by Django 3.2.19 on 2026-06-05 10:05

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20260604_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube URL of the trailer', null=True, validators=[movies.models.validate_youtube_url]),
        ),
    ]
