# Generated by Django 3.2.19 on 2026-06-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
