# Generated by Django 3.2.19 on 2026-06-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_fix_legacy_idempotency_keys'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'booked_at'], name='movies_book_status_40a788_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'movie'], name='movies_book_status_f3c141_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'created_at'], name='movies_paym_status_e480bb_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['theater', 'is_booked'], name='movies_seat_theater_7e5f1d_idx'),
        ),
    ]
