# Generated by Django 3.2.19 on 2026-06-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20260612_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailqueueitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10),
        ),
    ]
